force-app/main/default/objects/Listing__c/Listing__c.object-meta.xml
<CustomObject>
    <description
  >A Listing represents the marketing collateral created by a Publisher about a particular App.</description>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing__c/fields/SubscriptionPlan__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionPlan__c</fullName>
    <label>SubscriptionPlan</label>
    <referenceTo>SubscriptionPlan__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing__c/recordTypes/Content.recordType-meta.xml
<RecordType>
    <fullName>Content</fullName>
    <active>true</active>
    <description>An AppExchange Content Listing</description>
    <label>Content</label>
</RecordType>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <description
  >A Publisher is the entity that created a Listing. A Publisher could be salesforce.com, Salesforce Labs, an ISV (independent software vendor), a SI (systems integrator), or a developer just wishing to share some code.</description>
    <label>Publisher</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionPlan__c/SubscriptionPlan__c.object-meta.xml
<CustomObject>
    <description
  >Subscription Plan fot the Listing, it could be either external (meaning that the billing management is managed outside of Appexchange) or Recurly (meaning that the Recurly API will be used instead).</description>
    <label>SubscriptionPlan</label>
    <nameField>
        <label>SubscriptionPlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubscriptionPlans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionPlan__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description
  >A subscription plan will be marked as inactive when it&apos;s deleted from Stripe side.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Charge__c.field-meta.xml
<CustomField>
    <fullName>Charge__c</fullName>
    <description>Charge price for the Subscription plan.</description>
    <inlineHelpText>Charge price for the Subscription plan.</inlineHelpText>
    <label>Charge</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>The currency for the charge.</description>
    <inlineHelpText>The currency for the charge.</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency for the charge of the listing.</description>
    <inlineHelpText>Frequency for the charge of the listing.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <label>Listing</label>
    <referenceTo>Listing__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/recordTypes/SelfCheckout.recordType-meta.xml
<RecordType>
    <fullName>SelfCheckout</fullName>
    <active>true</active>
    <description
  >Represents that the billing management used is a Self Checkout system.</description>
    <label>SelfCheckout</label>
</RecordType>

force-app/main/default/classes/SubscriptionPlansSyncBatch.cls
/*
 * Batch to sync One-Time plans into Stripe
 * Since Stripe start using One-Time plans, and the new Checkout will use APIs that will implement this ones, we need to have legacy
 * Subscription Plans sync into Stripe so it wont brake
 * Once all Plans are migrated and old Publishing Console is no longed available, this batch wont be used any more
 */
public with sharing class SubscriptionPlansSyncBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
  public void execute(SchedulableContext sc) {
    SubscriptionPlansSyncBatch b = new SubscriptionPlansSyncBatch();
    Database.executeBatch(b);
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    // collect the batches of records or objects to be passed to execute
    // Limit to 100 because of callout limits
    String query = 'SELECT Id, Name, ExternalId__c, Charge__c, Currency__c, Listing__r.Name, Listing__r.Publisher__r.BillingLiveAccessToken__c FROM SubscriptionPlan__c WHERE ExternalId__c = null AND Active__c = true AND Frequency__c = \'One-Time\' AND RecordType.DeveloperName = \'SelfCheckout\' AND Listing__r.Publisher__r.BillingLiveAccessToken__c != null AND Listing__r.Publisher__r.CheckoutSignUpStatus__c = \'Live\' LIMIT 100';
    return Database.getQueryLocator(query);
  }

  public void execute(
    Database.BatchableContext bc,
    List<SubscriptionPlan__c> records
  ) {
    List<SubscriptionPlan__c> toUpdate = new List<SubscriptionPlan__c>();
    // process each batch of records
    for (SubscriptionPlan__c sp : records) {
      // Make callout to stripe with each Subscription Plan
      Map<String, String> params = new Map<String, String>();
      params.put(
        'unit_amount',
        String.valueOf(Integer.valueOf(sp.Charge__c * 100))
      );
      params.put('currency', sp.Currency__c.toLowerCase());
      params.put('product_data[name]', sp.Listing__r.Name);

      // Set Body
      Map<String, Object> resp = SubscriptionPlansSyncBatch.makeCallout(
        getURLStringFromMap(params),
        sp.Listing__r.Publisher__r.BillingLiveAccessToken__c
      );
      String priceId = String.valueOf(resp.get('id'));
      if (priceId != null) {
        sp.ExternalId__c = priceId;
        toUpdate.add(sp);
      }
    }
    if (!toUpdate.isEmpty()) {
      update toUpdate;
    }
  }

  public static String getURLStringFromMap(Map<String, String> stringMap) {
    String ret = '', separator;
    Boolean flagSeparator = false;
    for (String s : stringMap.keySet()) {
      if (!String.isEmpty((String) stringMap.get(s))) {
        separator = flagSeparator ? '&' : '';
        ret +=
          separator +
          s +
          '=' +
          EncodingUtil.urlEncode((String) stringMap.get(s), 'UTF-8');
        flagSeparator = true;
      }
    }
    return ret;
  }

  private static Map<String, Object> makeCallout(
    String body,
    String APIAccessKey
  ) {
    String url;
    Http h = new Http();
    HttpRequest req = new HttpRequest();
    String uri = 'https://api.stripe.com/v1/prices';
    req.setHeader(
      'Authorization',
      'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(APIAccessKey + ':'))
    );
    req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
    req.setEndpoint(uri);
    req.setMethod('POST');
    req.setBody(body);

    try {
      HttpResponse response = h.send(req);
      String responseBody;
      if (!String.isEmpty(response.getBody())) {
        responseBody = response.getBody();
      }

      return (Map<String, Object>) JSON.deserializeUntyped(responseBody);
    } catch (System.Exception e) {
      system.debug(e.getMessage());
    }

    return null;
  }

  public void finish(Database.BatchableContext bc) {
    // execute any post-processing operations
  }
}