force-app/main/default/objects/Listing__c/Listing__c.object-meta.xml
<CustomObject>
    <description
  >A Listing represents the marketing collateral created by a Publisher about a particular App.</description>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listing__c/fields/SubscriptionPlan__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionPlan__c</fullName>
    <label>SubscriptionPlan</label>
    <referenceTo>SubscriptionPlan__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <description
  >A Publisher is the entity that created a Listing. A Publisher could be salesforce.com, Salesforce Labs, an ISV (independent software vendor), a SI (systems integrator), or a developer just wishing to share some code.</description>
    <label>Publisher</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Publisher__c/fields/BillingLiveAccessToken__c.field-meta.xml
<CustomField>
    <fullName>BillingLiveAccessToken__c</fullName>
    <description>Live Stripe Access Token retrieved from signup.</description>
        <label>BillingLiveAccessToken</label>
        <length>255</length>
        <type>Text</type>
</CustomField>

force-app/main/default/objects/Publisher__c/fields/CheckoutSignUpStatus__c.field-meta.xml
<CustomField>
    <fullName>CheckoutSignUpStatus__c</fullName>
    <description
  >Indicates what stage in the review process the Listing is in for the Marketplace.</description>
    <inlineHelpText
  >Indicates what stage in the review process the Listing is in for the Marketplace.</inlineHelpText>
    <label>Checkout Signup Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
                <default>true</default>
                <label>Live</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>SignUp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/SubscriptionPlan__c.object-meta.xml
<CustomObject>
    <description
  >Subscription Plan fot the Listing, it could be either external (meaning that the billing management is managed outside of Appexchange) or Recurly (meaning that the Recurly API will be used instead).</description>
    <label>SubscriptionPlan</label>
    <nameField>
        <label>SubscriptionPlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubscriptionPlans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriptionPlan__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description
  >A subscription plan will be marked as inactive when it&apos;s deleted from Stripe side.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Charge__c.field-meta.xml
<CustomField>
    <fullName>Charge__c</fullName>
    <description>Charge price for the Subscription plan.</description>
    <inlineHelpText>Charge price for the Subscription plan.</inlineHelpText>
    <label>Charge</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>The currency for the charge.</description>
    <inlineHelpText>The currency for the charge.</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency for the charge of the listing.</description>
    <inlineHelpText>Frequency for the charge of the listing.</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <label>Listing</label>
    <referenceTo>Listing__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriptionPlan__c/recordTypes/SelfCheckout.recordType-meta.xml
<RecordType>
    <fullName>SelfCheckout</fullName>
    <active>true</active>
    <description
  >Represents that the billing management used is a Self Checkout system.</description>
    <label>SelfCheckout</label>
</RecordType>

force-app/main/default/classes/SubscriptionPlansSyncBatchTest.cls
@isTest
private class SubscriptionPlansSyncBatchTest {
  @isTest
  static void syncPlans_NoPlans() {
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();
  }

  @isTest
  static void syncPlans_OneTime() {
    RecordType rt = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'SelfCheckout'
      LIMIT 1
    ];
    Publisher__c pub = new Publisher__c(
      Name = 'Publisher 1',
      BillingLiveAccessToken__c = 'Stripe_test',
      CheckoutSignUpStatus__c = 'Live'
    );
    insert pub;
    Listing__c listing = new Listing__c(
      Name = 'Listing 1',
      Publisher__c = pub.Id
    );
    insert listing;
    SubscriptionPlan__c sp1 = new SubscriptionPlan__c(
      Name = 'Test',
      Charge__c = 1000,
      Active__c = true,
      Currency__c = 'USD',
      Frequency__c = 'One-Time',
      RecordTypeId = rt.Id,
      Listing__c = listing.Id
    );
    insert sp1;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();

    SubscriptionPlan__c sp = [
      SELECT Id, Name, ExternalId__c
      FROM SubscriptionPlan__c
      WHERE Id = :sp1.Id
    ];
    System.assertEquals(
      'price_1LUwmiHBeka1JxuI40lJAKXf',
      sp.ExternalId__c,
      'The Stripe Id is invalid'
    );
  }

  @isTest
  static void syncPlans_PlansAlreadySync() {
    RecordType rt = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'SelfCheckout'
      LIMIT 1
    ];
    Publisher__c pub = new Publisher__c(
      Name = 'Publisher 1',
      BillingLiveAccessToken__c = 'Stripe_test',
      CheckoutSignUpStatus__c = 'Live'
    );
    insert pub;
    Listing__c listing = new Listing__c(
      Name = 'Listing 1',
      Publisher__c = pub.Id
    );
    insert listing;
    SubscriptionPlan__c sp1 = new SubscriptionPlan__c(
      Name = 'Test',
      Charge__c = 1000,
      Active__c = true,
      Currency__c = 'USD',
      Frequency__c = 'One-Time',
      RecordTypeId = rt.Id,
      Listing__c = listing.Id,
      ExternalId__c = 'testId'
    );
    insert sp1;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();

    SubscriptionPlan__c sp = [
      SELECT Id, Name, ExternalId__c
      FROM SubscriptionPlan__c
      WHERE Id = :sp1.Id
    ];
    System.assertEquals(
      sp1.ExternalId__c,
      sp.ExternalId__c,
      'The Stripe Id is invalid'
    );
  }

  @isTest
  static void syncPlans_OneTimeAndRecurring() {
    RecordType rt = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'SelfCheckout'
      LIMIT 1
    ];
    Publisher__c pub = new Publisher__c(
      Name = 'Publisher 1',
      BillingLiveAccessToken__c = 'Stripe_test',
      CheckoutSignUpStatus__c = 'Live'
    );
    insert pub;
    Listing__c listing = new Listing__c(
      Name = 'Listing 1',
      Publisher__c = pub.Id
    );
    insert listing;

    List<SubscriptionPlan__c> plans = new List<SubscriptionPlan__c>();
    plans.add(
      new SubscriptionPlan__c(
        Name = 'Test1',
        Charge__c = 1000,
        Active__c = true,
        Currency__c = 'USD',
        Frequency__c = 'One-Time',
        RecordTypeId = rt.Id,
        Listing__c = listing.Id
      )
    );
    plans.add(
      new SubscriptionPlan__c(
        Name = 'Test2',
        Charge__c = 1000,
        Active__c = true,
        Currency__c = 'USD',
        Frequency__c = 'Recurring',
        RecordTypeId = rt.Id,
        ExternalId__c = 'testId',
        Listing__c = listing.Id
      )
    );
    insert plans;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();

    List<SubscriptionPlan__c> plans1 = [
      SELECT Id, Name, ExternalId__c
      FROM SubscriptionPlan__c
    ];
    System.assertEquals(
      'price_1LUwmiHBeka1JxuI40lJAKXf',
      plans1.get(0).ExternalId__c,
      'The Stripe Id is invalid'
    );
    System.assertEquals(
      'testId',
      plans1.get(1).ExternalId__c,
      'The Stripe Id is invalid'
    );
  }

  @isTest
  static void syncPlans_OneTimePublisherNone() {
    RecordType rt = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'SelfCheckout'
      LIMIT 1
    ];
    Publisher__c pub = new Publisher__c(
      Name = 'Publisher 1',
      BillingLiveAccessToken__c = 'Stripe_test',
      CheckoutSignUpStatus__c = 'None'
    );
    insert pub;
    Listing__c listing = new Listing__c(
      Name = 'Listing 1',
      Publisher__c = pub.Id
    );
    insert listing;
    SubscriptionPlan__c sp1 = new SubscriptionPlan__c(
      Name = 'Test',
      Charge__c = 1000,
      Active__c = true,
      Currency__c = 'USD',
      Frequency__c = 'One-Time',
      RecordTypeId = rt.Id,
      Listing__c = listing.Id
    );
    insert sp1;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();

    SubscriptionPlan__c sp = [
      SELECT Id, Name, ExternalId__c
      FROM SubscriptionPlan__c
      WHERE Id = :sp1.Id
    ];
    System.assertEquals(null, sp.ExternalId__c, 'The Stripe Id is invalid');
  }

  @isTest
  static void syncPlans_NoPublisherAccessToken() {
    RecordType rt = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'SelfCheckout'
      LIMIT 1
    ];
    Publisher__c pub = new Publisher__c(
      Name = 'Publisher 1',
      CheckoutSignUpStatus__c = 'Live'
    );
    insert pub;
    Listing__c listing = new Listing__c(
      Name = 'Listing 1',
      Publisher__c = pub.Id
    );
    insert listing;
    SubscriptionPlan__c sp1 = new SubscriptionPlan__c(
      Name = 'Test',
      Charge__c = 1000,
      Active__c = true,
      Currency__c = 'USD',
      Frequency__c = 'One-Time',
      RecordTypeId = rt.Id,
      Listing__c = listing.Id
    );
    insert sp1;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();

    SubscriptionPlan__c sp = [
      SELECT Id, Name, ExternalId__c
      FROM SubscriptionPlan__c
      WHERE Id = :sp1.Id
    ];
    System.assertEquals(null, sp.ExternalId__c, 'The Stripe Id is invalid');
  }

  @isTest
  static void syncPlans_NoListingRelated() {
    RecordType rt = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'SelfCheckout'
      LIMIT 1
    ];
    Publisher__c pub = new Publisher__c(
      Name = 'Publisher 1',
      CheckoutSignUpStatus__c = 'Live'
    );
    insert pub;
    Listing__c listing = new Listing__c(
      Name = 'Listing 1',
      Publisher__c = pub.Id
    );
    insert listing;
    SubscriptionPlan__c sp1 = new SubscriptionPlan__c(
      Name = 'Test',
      Charge__c = 1000,
      Active__c = true,
      Currency__c = 'USD',
      Frequency__c = 'One-Time',
      RecordTypeId = rt.Id
    );
    insert sp1;

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new SyncBatchMock());
    Database.executeBatch(new SubscriptionPlansSyncBatch());
    Test.stopTest();

    SubscriptionPlan__c sp = [
      SELECT Id, Name, ExternalId__c
      FROM SubscriptionPlan__c
      WHERE Id = :sp1.Id
    ];
    System.assertEquals(null, sp.ExternalId__c, 'The Stripe Id is invalid');
  }
}